export { default as Panel } from './Panel.vue'
export { default as PanelContent } from './PanelContent.vue'
export { default as PanelFooter } from './PanelFooter.vue'
export { default as PanelHeader } from './PanelHeader.vue'
export { default as PanelItem } from './PanelItem.vue'
export { default as PanelTitle } from './PanelTitle.vue'
