<template>
    <WorkbenchLayout>
        <Head title="Sidebar navigation workbench" />

        <section class="mb-8 max-w-3xl">
            <Badge variant="outline">PHP-driven navigation</Badge>
            <h1 class="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Sidebar navigation</h1>
            <p class="mt-3 text-base leading-7 text-muted-foreground">
                This menu, its inline SVG icons, badges, breadcrumbs, and tabs are all assembled by Laravel and passed through Inertia.
            </p>
        </section>

        <SidebarProvider
            v-model:open="sidebarOpen"
            class="relative min-h-[42rem] overflow-hidden rounded-xl border bg-sidebar shadow-sm"
        >
            <Sidebar
                collapsible="icon"
                variant="inset"
                class="absolute h-full"
            >
                <SidebarHeader class="border-b border-sidebar-border">
                    <div class="flex h-8 items-center gap-2 px-2 group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:px-0">
                        <span class="grid size-6 shrink-0 place-items-center rounded-md bg-sidebar-primary text-[10px] font-bold text-sidebar-primary-foreground">
                            ST
                        </span>
                        <span class="truncate text-sm font-semibold group-data-[collapsible=icon]:hidden">Backend menu</span>
                    </div>
                </SidebarHeader>

                <SidebarContent>
                    <SidebarNavigation :menu="menu" />
                </SidebarContent>

                <SidebarFooter class="border-t border-sidebar-border">
                    <p class="px-2 text-xs leading-5 text-sidebar-foreground/70 group-data-[collapsible=icon]:hidden">
                        Nested links and counts are serialized from MenuItem instances.
                    </p>
                </SidebarFooter>
                <SidebarRail />
            </Sidebar>

            <SidebarInset class="min-h-[42rem] overflow-hidden">
                <header class="flex min-h-16 flex-wrap items-center gap-3 border-b px-4 sm:px-6">
                    <SidebarTrigger />
                    <Separator orientation="vertical" class="h-4" />
                    <BreadcrumbNavigation :list="breadcrumbs" />
                    <Badge variant="secondary" class="ml-auto">
                        {{ sidebarOpen ? 'Expanded' : 'Collapsed' }}
                    </Badge>
                </header>

                <div class="flex flex-1 flex-col gap-6 p-4 sm:p-6">
                    <div>
                        <p class="text-xs font-medium tracking-wide text-muted-foreground uppercase">Backend-selected action</p>
                        <div class="mt-2 flex flex-wrap items-center gap-3">
                            <h2 class="text-2xl font-semibold tracking-tight">{{ action || 'Home' }}</h2>
                            <Badge v-if="action" variant="outline">Route parameter</Badge>
                        </div>
                    </div>

                    <TabsNavigation :menu="tabs" class="max-w-full overflow-x-auto" />

                    <div class="grid gap-4 md:grid-cols-2">
                        <Card>
                            <CardHeader>
                                <CardTitle>Server-owned structure</CardTitle>
                                <CardDescription>
                                    Follow a nested sidebar item or tab to send a new optional action parameter to Laravel.
                                </CardDescription>
                            </CardHeader>
                            <CardContent class="flex flex-col gap-3 text-sm leading-6 text-muted-foreground">
                                <p>The active item is resolved against the URL generated by the named workbench route.</p>
                                <p>Tab visits preserve scroll while the selected label and breadcrumb come back from the controller.</p>
                            </CardContent>
                        </Card>

                        <Card>
                            <CardHeader>
                                <CardTitle>Collapse-aware navigation</CardTitle>
                                <CardDescription>
                                    Use the trigger or press <Kbd>⌘ B</Kbd> to compare both states.
                                </CardDescription>
                            </CardHeader>
                            <CardContent>
                                <div class="grid grid-cols-3 gap-3 text-center">
                                    <div class="rounded-lg border bg-muted/30 p-3">
                                        <p class="text-xl font-semibold">2</p>
                                        <p class="mt-1 text-xs text-muted-foreground">Nested levels</p>
                                    </div>
                                    <div class="rounded-lg border bg-muted/30 p-3">
                                        <p class="text-xl font-semibold">4</p>
                                        <p class="mt-1 text-xs text-muted-foreground">Live badges</p>
                                    </div>
                                    <div class="rounded-lg border bg-muted/30 p-3">
                                        <p class="text-xl font-semibold">3</p>
                                        <p class="mt-1 text-xs text-muted-foreground">Backend tabs</p>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </SidebarInset>
        </SidebarProvider>
    </WorkbenchLayout>
</template>

<script setup lang="ts">
import { Badge } from '@/Components/Base/Badge'
import { BreadcrumbNavigation } from '@/Components/Base/Breadcrumb'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/Base/Card'
import { Kbd } from '@/Components/Base/Kbd'
import { Separator } from '@/Components/Base/Separator'
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarInset,
    SidebarNavigation,
    SidebarProvider,
    SidebarRail,
    SidebarTrigger,
} from '@/Components/Base/Sidebar'
import { TabsNavigation } from '@/Components/Base/Tabs'
import WorkbenchLayout from '@/Docs/Layouts/WorkbenchLayout.vue'
import { Head } from '@inertiajs/vue3'
import { ref } from 'vue'

type BackendMenuItem = {
    title: string
    action?: {
        url: string
        external?: boolean
        preserveScroll?: boolean
        preserveState?: boolean
    } | null
    active?: Array<{ path: string } | { route: string, params?: Record<string, unknown> }>
    badge?: string | null
    children?: BackendMenu
    icon?: { src: string } | null
}

type BackendMenu = BackendMenuItem[]

defineProps<{
    action: string | null
    breadcrumbs: BackendMenu
    menu: BackendMenu
    tabs: BackendMenu
}>()

const sidebarOpen = ref(true)
</script>
