<?php

return [
    'github_url' => 'https://github.com/stacktracelabs/ui',
    'registry_url' => env('STACKTRACE_UI_REGISTRY_URL', 'https://ui.stacktrace.sk/r'),

    'navigation' => [
        [
            'title' => 'Getting Started',
            'items' => [
                ['title' => 'Introduction', 'href' => '/docs', 'component' => 'Docs/Introduction'],
                ['title' => 'Installation', 'href' => '/docs/installation', 'component' => 'Docs/Installation'],
                ['title' => 'Frontend Package', 'href' => '/docs/frontend-package', 'component' => 'Docs/FrontendPackage'],
            ],
        ],
        [
            'title' => 'Fundamentals',
            'items' => [
                ['title' => 'Composition', 'href' => '/docs/fundamentals/composition', 'component' => 'Docs/Fundamentals/Composition'],
            ],
        ],
        [
            'title' => 'Components',
            'items' => [
                ['title' => 'Accordion', 'href' => '/docs/components/accordion', 'component' => 'Docs/Components/Accordion'],
                ['title' => 'Alert', 'href' => '/docs/components/alert', 'component' => 'Docs/Components/Alert'],
                ['title' => 'Alert Dialog', 'href' => '/docs/components/alert-dialog', 'component' => 'Docs/Components/AlertDialog'],
                ['title' => 'Aspect Ratio', 'href' => '/docs/components/aspect-ratio', 'component' => 'Docs/Components/AspectRatio'],
                ['title' => 'Attachment', 'href' => '/docs/components/attachment', 'component' => 'Docs/Components/Attachment'],
                ['title' => 'Avatar', 'href' => '/docs/components/avatar', 'component' => 'Docs/Components/Avatar'],
                ['title' => 'Badge', 'href' => '/docs/components/badge', 'component' => 'Docs/Components/Badge'],
                ['title' => 'Breadcrumb', 'href' => '/docs/components/breadcrumb', 'component' => 'Docs/Components/Breadcrumb'],
                ['title' => 'Bubble', 'href' => '/docs/components/bubble', 'component' => 'Docs/Components/Bubble'],
                ['title' => 'Button', 'href' => '/docs/components/button', 'component' => 'Docs/Components/Button'],
                ['title' => 'Button Group', 'href' => '/docs/components/button-group', 'component' => 'Docs/Components/ButtonGroup'],
                ['title' => 'Calendar', 'href' => '/docs/components/calendar', 'component' => 'Docs/Components/Calendar'],
                ['title' => 'Card', 'href' => '/docs/components/card', 'component' => 'Docs/Components/Card'],
                ['title' => 'Carousel', 'href' => '/docs/components/carousel', 'component' => 'Docs/Components/Carousel'],
                ['title' => 'Chart', 'href' => '/docs/components/chart', 'component' => 'Docs/Components/Chart'],
                ['title' => 'Checkbox', 'href' => '/docs/components/checkbox', 'component' => 'Docs/Components/Checkbox'],
                ['title' => 'Collapsible', 'href' => '/docs/components/collapsible', 'component' => 'Docs/Components/Collapsible'],
                ['title' => 'Combobox', 'href' => '/docs/components/combobox', 'component' => 'Docs/Components/Combobox'],
                ['title' => 'Command', 'href' => '/docs/components/command', 'component' => 'Docs/Components/Command'],
                ['title' => 'Confirmation Dialog', 'href' => '/docs/components/confirmation-dialog', 'component' => 'Docs/Components/ConfirmationDialog'],
                ['title' => 'Context Menu', 'href' => '/docs/components/context-menu', 'component' => 'Docs/Components/ContextMenu'],
                ['title' => 'Data Table', 'href' => '/docs/components/data-table', 'component' => 'Docs/Components/DataTable'],
                ['title' => 'Date Input', 'href' => '/docs/components/date-input', 'component' => 'Docs/Components/DateInput'],
                ['title' => 'Date Picker', 'href' => '/docs/components/date-picker', 'component' => 'Docs/Components/DatePicker'],
                ['title' => 'Date Range Picker', 'href' => '/docs/components/date-range-picker', 'component' => 'Docs/Components/DateRangePicker'],
                ['title' => 'Date Time Input', 'href' => '/docs/components/date-time-input', 'component' => 'Docs/Components/DateTimeInput'],
                ['title' => 'Dialog', 'href' => '/docs/components/dialog', 'component' => 'Docs/Components/Dialog'],
                ['title' => 'Drawer', 'href' => '/docs/components/drawer', 'component' => 'Docs/Components/Drawer'],
                ['title' => 'Dropdown Menu', 'href' => '/docs/components/dropdown-menu', 'component' => 'Docs/Components/DropdownMenu'],
                ['title' => 'Empty', 'href' => '/docs/components/empty', 'component' => 'Docs/Components/Empty'],
                ['title' => 'Field', 'href' => '/docs/components/field', 'component' => 'Docs/Components/Field'],
                ['title' => 'Filter', 'href' => '/docs/components/filter', 'component' => 'Docs/Components/Filter'],
                ['title' => 'Form', 'href' => '/docs/components/form', 'component' => 'Docs/Components/Form'],
                ['title' => 'Hover Card', 'href' => '/docs/components/hover-card', 'component' => 'Docs/Components/HoverCard'],
                ['title' => 'Input', 'href' => '/docs/components/input', 'component' => 'Docs/Components/Input'],
                ['title' => 'Input Group', 'href' => '/docs/components/input-group', 'component' => 'Docs/Components/InputGroup'],
                ['title' => 'Input OTP', 'href' => '/docs/components/input-otp', 'component' => 'Docs/Components/InputOTP'],
                ['title' => 'Item', 'href' => '/docs/components/item', 'component' => 'Docs/Components/Item'],
                ['title' => 'Kbd', 'href' => '/docs/components/kbd', 'component' => 'Docs/Components/Kbd'],
                ['title' => 'Label', 'href' => '/docs/components/label', 'component' => 'Docs/Components/Label'],
                ['title' => 'Logo', 'href' => '/docs/components/logo', 'component' => 'Docs/Components/Logo'],
                ['title' => 'Marker', 'href' => '/docs/components/marker', 'component' => 'Docs/Components/Marker'],
                ['title' => 'Menubar', 'href' => '/docs/components/menubar', 'component' => 'Docs/Components/Menubar'],
                ['title' => 'Message', 'href' => '/docs/components/message', 'component' => 'Docs/Components/Message'],
                ['title' => 'Message Scroller', 'href' => '/docs/components/message-scroller', 'component' => 'Docs/Components/MessageScroller'],
                ['title' => 'Native Select', 'href' => '/docs/components/native-select', 'component' => 'Docs/Components/NativeSelect'],
                ['title' => 'Navigation Menu', 'href' => '/docs/components/navigation-menu', 'component' => 'Docs/Components/NavigationMenu'],
                ['title' => 'Number Field', 'href' => '/docs/components/number-field', 'component' => 'Docs/Components/NumberField'],
                ['title' => 'Pagination', 'href' => '/docs/components/pagination', 'component' => 'Docs/Components/Pagination'],
                ['title' => 'Panel', 'href' => '/docs/components/panel', 'component' => 'Docs/Components/Panel'],
                ['title' => 'Pin Input', 'href' => '/docs/components/pin-input', 'component' => 'Docs/Components/PinInput'],
                ['title' => 'Popover', 'href' => '/docs/components/popover', 'component' => 'Docs/Components/Popover'],
                ['title' => 'Progress', 'href' => '/docs/components/progress', 'component' => 'Docs/Components/Progress'],
                ['title' => 'Radio Group', 'href' => '/docs/components/radio-group', 'component' => 'Docs/Components/RadioGroup'],
                ['title' => 'Range Calendar', 'href' => '/docs/components/range-calendar', 'component' => 'Docs/Components/RangeCalendar'],
                ['title' => 'Resizable', 'href' => '/docs/components/resizable', 'component' => 'Docs/Components/Resizable'],
                ['title' => 'Scroll Area', 'href' => '/docs/components/scroll-area', 'component' => 'Docs/Components/ScrollArea'],
                ['title' => 'Select', 'href' => '/docs/components/select', 'component' => 'Docs/Components/Select'],
                ['title' => 'Separator', 'href' => '/docs/components/separator', 'component' => 'Docs/Components/Separator'],
                ['title' => 'Sheet', 'href' => '/docs/components/sheet', 'component' => 'Docs/Components/Sheet'],
                ['title' => 'Sidebar', 'href' => '/docs/components/sidebar', 'component' => 'Docs/Components/Sidebar'],
                ['title' => 'Skeleton', 'href' => '/docs/components/skeleton', 'component' => 'Docs/Components/Skeleton'],
                ['title' => 'Slider', 'href' => '/docs/components/slider', 'component' => 'Docs/Components/Slider'],
                ['title' => 'Sonner', 'href' => '/docs/components/sonner', 'component' => 'Docs/Components/Sonner'],
                ['title' => 'Spinner', 'href' => '/docs/components/spinner', 'component' => 'Docs/Components/Spinner'],
                ['title' => 'Stepper', 'href' => '/docs/components/stepper', 'component' => 'Docs/Components/Stepper'],
                ['title' => 'Switch', 'href' => '/docs/components/switch', 'component' => 'Docs/Components/Switch'],
                ['title' => 'Table', 'href' => '/docs/components/table', 'component' => 'Docs/Components/Table'],
                ['title' => 'Tabs', 'href' => '/docs/components/tabs', 'component' => 'Docs/Components/Tabs'],
                ['title' => 'Tags Input', 'href' => '/docs/components/tags-input', 'component' => 'Docs/Components/TagsInput'],
                ['title' => 'Textarea', 'href' => '/docs/components/textarea', 'component' => 'Docs/Components/Textarea'],
                ['title' => 'Toggle', 'href' => '/docs/components/toggle', 'component' => 'Docs/Components/Toggle'],
                ['title' => 'Toggle Group', 'href' => '/docs/components/toggle-group', 'component' => 'Docs/Components/ToggleGroup'],
                ['title' => 'Tooltip', 'href' => '/docs/components/tooltip', 'component' => 'Docs/Components/Tooltip'],
            ],
        ],
        [
            'title' => 'Composables',
            'items' => [
                ['title' => 'useFilter', 'href' => '/docs/composables/filter', 'component' => 'Docs/Composables/Filter'],
                ['title' => 'useFlash', 'href' => '/docs/composables/flash', 'component' => 'Docs/Composables/Flash'],
                ['title' => 'useNavigation', 'href' => '/docs/composables/navigation', 'component' => 'Docs/Composables/Navigation'],
                ['title' => 'useToggle', 'href' => '/docs/composables/toggle', 'component' => 'Docs/Composables/Toggle'],
            ],
        ],
        [
            'title' => 'Utilities',
            'items' => [
                ['title' => 'asyncRouter', 'href' => '/docs/utilities/async-router', 'component' => 'Docs/Utilities/AsyncRouter'],
            ],
        ],
        [
            'title' => 'Types',
            'items' => [
                ['title' => 'SelectOption', 'href' => '/docs/types/select-option', 'component' => 'Docs/Types/SelectOption'],
                ['title' => 'SVGSource', 'href' => '/docs/types/svg-source', 'component' => 'Docs/Types/SVGSource'],
            ],
        ],
    ],
];
