name: split-monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Branch Split of stacktrace/ui
        uses: symplify/github-action-monorepo-split@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'package-ui'
          repository_organization: 'stacktracelabs'
          repository_name: 'laravel-ui'
          user_name: 'Peter Stovka'
          user_email: 'stovka.peter@gmail.com'
          branch: main
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tag Split of stacktrace/ui
        uses: symplify/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${{ steps.previous-tag.outputs.tag }}
          branch: main
          package_directory: 'package-ui'
          repository_organization: 'stacktracelabs'
          repository_name: 'laravel-ui'
          user_name: 'Peter Stovka'
          user_email: 'stovka.peter@gmail.com'
